[12/Oct/2025 05:18:41] "GET /blog/login/ HTTP/1.1" 200 10702
[12/Oct/2025 05:18:47] "GET /blog/dashboard/ HTTP/1.1" 200 15706
Internal Server Error: /blog/create/
Traceback (most recent call last):
  File "/home/zecustomizer/projects/ambassadors/daycare/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/zecustomizer/projects/ambassadors/daycare/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zecustomizer/projects/ambassadors/daycare/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zecustomizer/projects/ambassadors/daycare/.venv/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zecustomizer/projects/ambassadors/daycare/blog/views.py", line 71, in wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zecustomizer/projects/ambassadors/daycare/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zecustomizer/projects/ambassadors/daycare/blog/views.py", line 299, in get
    return render(request, self.template_name, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zecustomizer/projects/ambassadors/daycare/.venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zecustomizer/projects/ambassadors/daycare/.venv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zecustomizer/projects/ambassadors/daycare/.venv/lib/python3.12/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: blog/create_article.html
[12/Oct/2025 05:19:16] "GET /blog/create/ HTTP/1.1" 500 114808
[12/Oct/2025 05:19:28] "GET /blog/login/ HTTP/1.1" 302 0
[12/Oct/2025 05:19:28] "GET /blog/dashboard/ HTTP/1.1" 200 15706
